# Generated by Django 5.1.4 on 2025-01-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('merchandising', '0001_initial'),
        ('personnel_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название причины')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание причины')),
            ],
            options={
                'verbose_name': 'Причина отсутствия',
                'verbose_name_plural': 'Причины отсутствия',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('work_phone', models.IntegerField(max_length=15, verbose_name='Рабочий телефон')),
                ('personal_phone', models.IntegerField(max_length=15, verbose_name='Личный телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('inn', models.IntegerField(max_length=12, verbose_name='ИНН')),
                ('snils', models.IntegerField(max_length=11, verbose_name='СНИЛС')),
                ('date_of_employment', models.DateTimeField(verbose_name='Дата приёма на работу')),
                ('date_of_medical', models.DateTimeField(verbose_name='Дата прохождения медосмотра')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandising.division', verbose_name='ID подразделения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='ID роли')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
