# Generated by Django 5.1.4 on 2025-01-05 11:17

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_records', '0003_alter_employee_inn_alter_employee_personal_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_presence', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=3, verbose_name='Дни присутствия'), size=None)),
                ('time_start', models.TimeField(verbose_name='Время начала смены')),
                ('time_end', models.TimeField(verbose_name='Время окончания смены')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel_records.employee', verbose_name='ID сотрудника')),
            ],
            options={
                'verbose_name': 'Расписание работника',
                'verbose_name_plural': 'Расписания работников',
            },
        ),
        migrations.CreateModel(
            name='ForeignPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Номер')),
                ('department_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Код подразделения выдачи')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('date_of_expiration', models.DateField(verbose_name='Дата окончания действия')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel_records.employee', verbose_name='ID сотрудника')),
            ],
            options={
                'verbose_name': 'Иностранный паспорт',
                'verbose_name_plural': 'Иностранные паспорта',
            },
        ),
        migrations.CreateModel(
            name='MilitaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('military_office_address', models.CharField(max_length=150, verbose_name='Адрес военкомата')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Место рождения')),
                ('education', models.CharField(max_length=150, verbose_name='Образование')),
                ('category', models.CharField(max_length=2, verbose_name='Категория')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel_records.employee', verbose_name='ID сотрудника')),
            ],
            options={
                'verbose_name': 'Военное удостоверение',
                'verbose_name_plural': 'Военные удостоверения',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=1, verbose_name='Пол')),
                ('seriya', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Серия')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Номер')),
                ('department_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Код подразделения выдачи')),
                ('registration_address', models.CharField(max_length=150, verbose_name='Адрес прописки')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel_records.employee', verbose_name='ID сотрудника')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
    ]
